spring:
  application:
    name: user-mgt-service

server:
  port: 7002
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/
  instance:
    hostname: localhost