spring:
  application:
    name: room-service

server:
  port: 7001
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7003/eureka/
  instance:
    hostname: localhost