spring:
  application:
    name: eureka-service

server:
  port: 7003

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    db-service:
      path: /room-service/**
      url: http://localhost:7001
    stock-service:
      path: /user-mgt-service/**
      url: http://localhost:7002
    ui-service:
      path:/ui-service/**
      url:http://localhost:7004